app/apps/lk/urls.py
from django.urls import path

from .views import *

app_name = 'LK'

urlpatterns = [
    path('', IndexView.as_view(), name="index"),

    path('catalog', CatalogView.as_view(), name="catalog"),
    path('catalog/add', CatalogCreateView.as_view(), name="catalog_add"),
    path('catalog/edit', CatalogEditView.as_view(), name="catalog_edit"),
    path('catalog/delete', CatalogDeleteView.as_view(), name="catalog_delete"),

    path('catalog/type/add', CatalogTypeCreateView.as_view(), name="catalog_type_add"),
    path('catalog/types/edit', CatalogTypeEditView.as_view(), name="catalog_type_edit"),
    path('catalog/types/delete', CatalogTypeDeleteView.as_view(), name="catalog_type_delete"),

    path('bars', BarsView.as_view(), name="bars"),
    path('bars/settings', BarSettingsView.as_view(), name="bars_settings"),
    path('product_remains_add', product_remains_add, name="product_remains_add"),
    path('link_question_to_bar_setting', link_question_to_bar_setting, name="link_question_to_bar_setting"),

    path('positions', PositionsView.as_view(), name="positions"),
    path('positions/edit', PositionsEditView.as_view(), name="position_edit"),
    path('positions/delete', PositionDeleteView.as_view(), name="position_delete"),

    path('jobs/add', JobAddView.as_view(), name="job_add"),

    path('bank', BankView.as_view(), name="bank"),
    path('bank/update', bank_update, name="update_bank"),
    path('bank/partners', BankPartnersView.as_view(), name="bank_partners"),
    path('bank/partners/edit', BankPartnerEditView.as_view(), name="edit_bank_partner"),
    path('bank/cards', BankCardsView.as_view(), name="bank_cards"),
    path('bank/cards/create', BankCardCreateView.as_view(), name="create_bank_card"),
    path('bank/cards/edit', BankCardEditView.as_view(), name="edit_bank_card"),

    path('money', MoneyView.as_view(), name="money"),
    path('money/update', update_money, name="update_money"),
    path('money/edit', MoneyEditView.as_view(), name="edit_money"),
    path('money/update_all', update_all_money_and_sessions, name="update_all_money"),
    path('money/differences', MoneyDifferencesView.as_view(), name="money_differences"),

    path('timetable', TimetableView.as_view(), name="timetable"),
    path('timetable/create', CreateTimetableView.as_view(), name="create_timetable"),
    path('timetable/edit', EditTimetableView.as_view(), name="edit_timetable"),
    path('timetable/delete', DeleteTimetableView.as_view(), name="delete_timetable"),
    path('timetable/update', TimetableUpdateView.as_view(), name="update_timetable"),

    path('expenses', ExpensesView.as_view(), name="expenses"),
    path('expenses/create', CreateExpenseView.as_view(), name="create_expense"),
    path('expenses/edit', EditExpenseView.as_view(), name="edit_expense"),
    path('expenses/delete', DeleteExpenseView.as_view(), name="delete_expense"),
    path('expenses/status', ExpenseStatusView.as_view(), name="status_expense"),

    path('salary', SalaryView.as_view(), name="salary"),
    path('salary/create', CreateSalaryView.as_view(), name="create_salary"),
    path('salary/edit', EditSalaryView.as_view(), name="edit_salary"),
    path('salary/delete', DeleteSalaryView.as_view(), name="delete_salary"),

    path('pays', PaysView.as_view(), name="pays"),
    path('pays/create', CreatePaysView.as_view(), name="create_pays"),
    path('pays/edit', EditPaysView.as_view(), name="edit_pays"),
    path('pays/delete', DeletePaysView.as_view(), name="delete_pays"),

    path('fines', FinesView.as_view(), name="fines"),
    path('fines/create', CreateFineView.as_view(), name="create_fine"),
    path('fines/edit', EditFinesView.as_view(), name="edit_fine"),
    path('fines/delete', DeleteFineView.as_view(), name="delete_fine"),

    path('employees', EmployeesView.as_view(), name="employees"),
    path('employees/create', CreateEmployeeView.as_view(), name="create_employee"),
    path('employees/edit', EditEmployeeView.as_view(), name="edit_employee"),
    path('employees/dismiss', DissmissEmployeeView.as_view(), name="dismiss_employee"),
    path('employees/return', ReturnToWorkEmployeeView.as_view(), name="return_employee"),

    path('tovar/arrivals', ArrivalsView.as_view(), name="tovar_arrivals"),
    path('tovar/arrivals/create', ArrivalCreateView.as_view(), name="tovar_arrival_create"),
    path('tovar/arrivals/edit', ArrivalEditView.as_view(), name="tovar_arrival_edit"),
    path('tovar/arrivals/delete', ArrivalDeleteView.as_view(), name="tovar_arrival_delete"),
    path('tovar/arrivals/invoices', ArrivalInvoicesView.as_view(), name="total_arrival_invoices"),
    path('tovar/arrivals/invoices/all', ArrivalInvoicesAllView.as_view()),
    path('tovar/requests', TovarRequestsView.as_view(), name="tovar_requests"),
    path('tovar/requests/edit', TovarRequestEditView.as_view(), name="tovar_request_edit"),
    path('tovar/requests/delete', TovarRequestDeleteView.as_view(), name="tovar_request_delete"),

    path('need_items', ItemDeficitView.as_view(), name="need_items"),
    path('need_items/create', NeedItemsCreateView.as_view(), name="need_items_create"),
    path('need_items/send', ItemDeficitSendView.as_view(), name="receive_need_item"),

    path('bars/actions', BarActionsView.as_view()),
    path('send_message_on_bar', SendMessageOnBar.as_view(), name="send_message_on_bar"),

    path('malfunctions', MalfunctionsView.as_view(), name="malfunctions"),
    path('malfunctions/create', MalfunctionCreateView.as_view(), name="malfunction_create"),
    path('malfunctions/delete', MalfunctionDeleteView.as_view(), name="malfunction_delete"),
    path('malfunctions/complete', MalfunctionCompleteView.as_view()),

    path('reviews', ReviewsView.as_view(), name="reviews"),
    path('reviews/create', review_create, name="review_create"),
    path('reviews/link_to_employee', review_link_to_employee, name="review_to_employee"),
  
    path('logs', LogsView.as_view(), name="logs"),
    path('logs/update', update_logs_view, name="update_logs"),
    path('logs/filter', LogsWithFilterView.as_view(), name="logs_with_filter"),

    path('purchaser', PurchaserView.as_view(), name='purchaser'),
    path('purchaser_get_table', get_table_for_purchaser, name='purchaser_get_table'),

    path('reports', ReportsView.as_view()),
    path('reports/money/update', ReportsMoneyUpdateView.as_view()),
    path('reports/expense_types_by_storage', ReportExpenseTypesByStorageView.as_view()),

    path('faq', FAQView.as_view(), name='faq'),
    path('faq/create', FAQCreateView.as_view(), name='create_faq'),
    path('faq/edit', FAQEditView.as_view(), name='edit_faq'),
    path('faq/delete', FAQDeleteView.as_view(), name='delete_faq'),
    path('faq/tags/create', FAQTagCreateView.as_view(), name='create_faq_tag'),
    path('faq/tags/edit', FAQTagEditView.as_view(), name='edit_faq_tag'),
    path('faq/tags/delete', FAQTagDeleteView.as_view(), name='delete_faq_tag')
]

app/config/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('', lambda x: redirect(settings.LOGIN_REDIRECT_URL)),

    path('lk/', include('apps.lk.urls')),
    path('iiko/', include('apps.iiko.urls')),
    path('bar/', include('apps.bar.urls')),
    path('repairer/', include('apps.repairer.urls')),
    path('api/', include('apps.api.urls')),
    path('purchaser/', include('apps.purchaser.urls')),
    path('admin/', include('apps.admin.urls')),
    path('brand_chief/', include('apps.brand_chief.urls')),

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
        re_path(r'^assets/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
    ]

app/apps/lk/models/managers.py
from django.db import models


class RoleManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().prefetch_related('can_view')


class ProfileManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().select_related('user', 'role')


class PositionManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().prefetch_related('linked_jobs')


class EmployeeManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().select_related('job_place', 'storage').prefetch_related('reviews')


class CatalogManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().prefetch_related('catalog_types')


class TestManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().prefetch_related('questions')


class TestResultManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().select_related('test', 'employee')


class PartnerManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().prefetch_related('expense_types', 'storages')


class CardManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().select_related('storage')


class StatementManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().select_related('linked', 'payer', 'recipient')


class FineManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().select_related('employee', 'reason')


class ExpenseManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().select_related('storage', 'expense_type', 'expense_source')


class ItemDeficitManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().select_related('owner', 'storage')


class ReviewManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().select_related('storage').prefetch_related('jobs')


class ExpenseStatusManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().select_related('expense')


class ProductRemainManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().select_related('storage', 'product')


class EmployeeLogManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().select_related('employee')


class FAQManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().prefetch_related('tags')

app/apps/api/views/lk_views.py
from rest_framework.viewsets import ModelViewSet

from apps.api.serializers import NavbarSerializer, RoleSerializer, ProfileSerializer, JobPlaceSerializer, \
    PositionSerializer, \
    EmployeeSerializer, CatalogTypeSerializer, CatalogSerializer, TestQuestionSerializer, TestSerializer, \
    TestResultSerializer, TelegramChatSerializer, CardSerializer, PartnerSerializer, StatementSerializer, \
    FineSerializer, ExpenseSerializer, LogsSerializer, ItemDeficitSerializer, MalfunctionSerializer, ReviewSerializer, \
    FAQSerializer, FAQTagSerializer
from apps.api.mixins import ModelViewSetMixin

from apps.lk.models import Navbar, Role, Profile, JobPlace, Position, Employee, Catalog, CatalogType, Log, Expense, \
    Fine, Statement, Card, Partner, TelegramChat, TestResult, Test, TestQuestion, ItemDeficit, Review, FAQ, FAQTag
from apps.repairer.models import Malfunction


class NavbarViewSet(ModelViewSetMixin):
    queryset = Navbar.objects.all()
    serializer_class = NavbarSerializer


class RoleViewSet(ModelViewSetMixin):
    queryset = Role.objects.all()
    serializer_class = RoleSerializer


class ProfileViewSet(ModelViewSetMixin):
    queryset = Profile.objects.all()
    serializer_class = ProfileSerializer


class JobPlaceViewSet(ModelViewSetMixin):
    queryset = JobPlace.objects.all()
    serializer_class = JobPlaceSerializer


class PositionViewSet(ModelViewSetMixin):
    queryset = Position.objects.all()
    serializer_class = PositionSerializer


class EmployeeViewSet(ModelViewSetMixin):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer

    def get_queryset(self):
        is_deleted = self.request.query_params.get('is_deleted')

        if is_deleted:
            return Employee.objects.filter(is_deleted=int(is_deleted))
        else:
            return Employee.objects.all()


class CatalogTypeViewSet(ModelViewSetMixin):
    queryset = CatalogType.objects.all()
    serializer_class = CatalogTypeSerializer


class CatalogViewSet(ModelViewSetMixin):
    queryset = Catalog.objects.all()
    serializer_class = CatalogSerializer


class TestQuestionViewSet(ModelViewSetMixin):
    queryset = TestQuestion.objects.all()
    serializer_class = TestQuestionSerializer


class TestViewSet(ModelViewSetMixin):
    queryset = Test.objects.all()
    serializer_class = TestSerializer


class TestResultViewSet(ModelViewSetMixin):
    queryset = TestResult.objects.all()
    serializer_class = TestResultSerializer


class TelegramChatViewSet(ModelViewSetMixin):
    queryset = TelegramChat.objects.all()
    serializer_class = TelegramChatSerializer


class PartnerViewSet(ModelViewSetMixin):
    queryset = Partner.objects.all()
    serializer_class = PartnerSerializer


class CardViewSet(ModelViewSetMixin):
    queryset = Card.objects.all()
    serializer_class = CardSerializer


class StatementViewSet(ModelViewSetMixin):
    queryset = Statement.objects.all()
    serializer_class = StatementSerializer


class FineViewSet(ModelViewSetMixin):
    queryset = Fine.objects.all()
    serializer_class = FineSerializer


class ExpenseViewSet(ModelViewSetMixin):
    queryset = Expense.objects.all()
    serializer_class = ExpenseSerializer


class LogsViewSet(ModelViewSetMixin):
    queryset = Log.objects.all()
    serializer_class = LogsSerializer


class ItemDeficitViewSet(ModelViewSetMixin):
    queryset = ItemDeficit.objects.all()
    serializer_class = ItemDeficitSerializer

    def get_queryset(self):
        without_success = self.request.query_params.get('without_success')

        if without_success and without_success == '1':
            return ItemDeficit.objects.exclude(status=3)
        else:
            return ItemDeficit.objects.filter(status=3)


class MalfunctionViewSet(ModelViewSetMixin):
    queryset = Malfunction.objects.all()
    serializer_class = MalfunctionSerializer


class ReviewViewSet(ModelViewSetMixin):
    queryset = Review.objects.all()
    serializer_class = ReviewSerializer


class FAQViewSet(ModelViewSet):
    queryset = FAQ.objects.all()
    serializer_class = FAQSerializer


class FAQTagViewSet(ModelViewSet):
    queryset = FAQTag.objects.all()
    serializer_class = FAQTagSerializer

app/templates/lk/positions/index.html
{% extends 'base.html' %}

{% block title %}Должности{% endblock %}
{% block page_title %}Должности{% endblock %}

{% block body %}
    <div class="container-xl">
        <div class="card rounded-3">
            <div class="card-header card-header-light rounded-top-3">
                <h3 class="card-title">Список позиций</h3>
                <div class="card-actions">
                    <a class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#position-add-modal">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-plus" width="24"
                             height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                             stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                            <path d="M12 5l0 14"></path>
                            <path d="M5 12l14 0"></path>
                        </svg>
                        Добавить позицию
                    </a>
                </div>
            </div>
            <div class="card-body">
                <table id="table" class="table table-sm table-striped table-hover table-bordered nowrap w-100">
                    <thead>
                    <tr>
                        <th>Позиция</th>
                        <th>Оклад</th>
                        <th></th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
        <div class="card rounded-3">
            <div class="card-header card-header-light rounded-top-3">
                <h3 class="card-title">Список должностей</h3>
                <div class="card-actions">
                    <a class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#job-add-modal">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-plus" width="24"
                             height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                             stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                            <path d="M12 5l0 14"></path>
                            <path d="M5 12l14 0"></path>
                        </svg>
                        Добавить должность
                    </a>
                </div>
            </div>
            <div class="card-body">
                <table id="table2" class="table table-sm table-striped table-hover table-bordered nowrap w-100">
                    <thead>
                    <tr>
                        <th>Должность</th>
                        <th>Оклад в основную (начис)</th>
                        <th>Оклад в усиление (начис)</th>
                        <th>Оклад в основную (получ)</th>
                        <th>Оклад в усиление (получ)</th>
                        <th></th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
    <div class="modal modal-blur fade" id="position-add-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Добавление новой позиции</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form action="{% url 'LK:positions' %}" name="form1" method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="alert alert-primary" role="alert" style="display: none;"
                             id="position-add-ctrl-alert">
                            <p class="mb-1">Приоритетный ID (чем больше, тем выше):</p>
                            <p class="mb-1">20-29 - бармены</p>
                            <p class="mb-1">10-19 - повара</p>
                            <p class="mb-0">0-9 - тех. служащие</p>
                        </div>
                        <div class="mb-2">
                            <div class="row">
                                <div class="col">
                                    <label class="form-label">Наименование</label>
                                    <input type="text" class="form-control" name="position-name"
                                           placeholder="Введите наименование позиции" required>
                                </div>
                                <div class="col">
                                    <label class="form-label">Привязать к</label>
                                    <select placeholder="Выберите должность" name="job_id" id="job_id" class="form-select" multiple required>
                                        <option></option>
                                        {% for job in jobs %}
                                            <option value="{{ job.id }}">{{ job.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="mb-2">
                            <div class="row">
                                <div class="col">
                                    <input class="form-control" name="position-oklad" type="tel" inputmode="numeric"
                                           placeholder="Оклад позиции" required>
                                </div>
                            </div>
                        </div>
                        <div class="mb-1">
                            <div class="row">
                                <div class="col-auto">
                                    <label class="form-check">
                                        <input class="form-check-input" type="checkbox" name="position-all-storages">
                                        <span class="form-check-label"><b>Все заведения</b></span>
                                    </label>
                                </div>
                                <div class="col-auto">
                                    <label class="form-check">
                                        <input class="form-check-input" type="checkbox" name="position-is-usil">
                                        <span class="form-check-label"><b>Усиление</b></span>
                                    </label>
                                </div>
                                <div class="col-auto">
                                    <label class="form-check">
                                        <input class="form-check-input" type="checkbox" name="position-is-calling">
                                        <span class="form-check-label"><b>Вызывной</b></span>
                                    </label>
                                </div>
                                <div class="col-auto">
                                    <label class="form-check">
                                        <input class="form-check-input" type="checkbox" name="position-has-percent">
                                        <span class="form-check-label"><b>Процент</b></span>
                                    </label>
                                </div>
                                <div class="col-auto">
                                    <label class="form-check">
                                        <input class="form-check-input" type="checkbox" name="position-has-premium">
                                        <span class="form-check-label"><b>Премия</b></span>
                                    </label>
                                </div>
                                <div class="col-auto">
                                    <label class="form-check">
                                        <input class="form-check-input" type="checkbox" name="position-is-trainee">
                                        <span class="form-check-label"><b>Стажер</b></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <input class="form-control" name="priority-id" type="tel" inputmode="numeric" min="1" max="99" placeholder="Расположение должности в списке от меньшего к большему" required>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn me-auto" data-bs-dismiss="modal">Закрыть</button>
                        <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">Добавить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal modal-blur fade" id="job-add-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Добавление новой должности</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form action="{% url 'LK:job_add' %}" method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="alert alert-danger" role="alert">
                            <p class="mb-1">При добавлении должности оставляйте оклад пустым в случае использования
                                стандартного расчета, если же иначе:
                                <br><b>Основная смена: введенный оклад; Усиление: введенный оклад / 2</b></p>
                        </div>

                        <div class="row">
                            <div class="col">
                                <label class="form-label">Наименование</label>
                                <input type="text" class="form-control" name="job-name"
                                       placeholder="Введите наименование должности" required>
                            </div>
                            <div class="col">
                                <label class="form-label">Оклад в усиление (начисление)</label>
                                <input type="tel" inputmode="numeric" class="form-control" name="job-gain-oklad-accrual">
                            </div>
                            <div class="col">
                                <label class="form-label">Оклад в основную (начисление)</label>
                                <input type="tel" inputmode="numeric" class="form-control" name="job-main-oklad-accrual">
                            </div>
                            <div class="col">
                                <label class="form-label">Оклад в усиление (получение)</label>
                                <input type="tel" inputmode="numeric" class="form-control" name="job-gain-oklad-receiving">
                            </div>
                            <div class="col">
                                <label class="form-label">Оклад в основную (получение)</label>
                                <input type="tel" inputmode="numeric" class="form-control" name="job-main-oklad-receiving">
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn me-auto" data-bs-dismiss="modal">Закрыть</button>
                        <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">Добавить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
            if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|BB|PlayBook|IEMobile|Windows Phone|Kindle|Silk|Opera Mini/i
                .test(navigator.userAgent)) {
                return false;
            } else document.getElementById('position-add-ctrl-alert').setAttribute('style', '')
            var table = run_datatable('table', '/api/positions', '/lk/positions', [{data: 'name'}, {data: 'args.oklad'}])
            var table2 = run_datatable('table2', '/api/jobplaces', '/lk/jobs', [{data: 'name'}, {data: 'main_shift_oklad_accrual'}, {data: 'gain_shift_oklad_accrual'},
                                                                                {data: 'main_shift_oklad_receiving'}, {data: 'gain_shift_oklad_receiving'}])
        });
    </script>
{% endblock %}

app/templates/lk/positions/job_edit.html
{% extends 'base.html' %}

{% block body %}
    <div class="container-xl">
        <div class="card rounded-3">
            <div class="card-header card-header-light rounded-top-3">
                Редактирование должности {{ row.name }}
            </div>
            <div class="card-body">
                <form action="{% url 'LK:job_edit' %}?id={{ row.id }}" method="post">
                    {% csrf_token %}
                    <div class="mb-2">
                        <div class="row">
                            <div class="col">
                                <label class="form-label">Наименование</label>
                                <input type="text" class="form-control" name="name"
                                       placeholder="Введите наименование должности" value="{{ row.name }}">
                            </div>
                        </div>
                    </div>
                    <div class="mb-2">
                        <div class="row">
                            <div class="col">
                                <label class="form-label">Оклад</label>
                                <input class="form-control" name="oklad" type="tel" inputmode="numeric"
                                       placeholder="Оклад позиции" value="{{ row.oklad }}">
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success w-100">Обновить</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}