app/apps/bar/urls.py
from django.urls import path

from . import views

app_name = "Bar"

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('timetable/delete', views.TimetableDeleteView.as_view(), name="timetable_delete"),

    path('expenses', views.ExpensesView.as_view(), name="expenses"),
    path('expenses/delete', views.ExpenseDeleteView.as_view(), name="expense_delete"),

    path('pays/add', views.PaysAddView.as_view(), name="pays_add"),
    path('pays/delete', views.PaysDeleteView.as_view(), name="pays_delete"),

    path('other', views.OtherView.as_view(), name="other"),

    path('salary', views.SalaryView.as_view(), name="salary"),
    path('salary/calculation', views.SalaryCalculationView.as_view(), name="salary_calculation"),
    path('salary/retired_employees', views.SalaryForRetiredEmployeesView.as_view(), name="salary_for_retired_employees"),
    path('salary/retired_employees/accrue', views.salary_for_retired_employee_accrue_view,
         name="salary_for_retired_employee_accrue"),
    path('salary/get_accrued_rows', views.SalaryAccruedRowsView.as_view()),

    path('requests/beer', views.TovarRequestBeerView.as_view(), name="tovar_request_beer"),
    path('requests/bar', views.TovarRequestBarView.as_view(), name="tovar_request_bar"),
    path('requests/products', views.TovarRequestProductsView.as_view(), name="tovar_request_products"),
    path('requests/hoz', views.TovarRequestHozView.as_view(), name="tovar_request_hoz"),
    path('requests/box', views.TovarRequestBoxView.as_view(), name="tovar_request_box"),
    path('requests/delete', views.TovarRequestDeleteView.as_view(), name="tovar_request_delete"),

    path('arrivals/beer', views.ArrivalBeerView.as_view(), name="arrival_beer"),
    path('arrivals/drinks', views.ArrivalDrinkView.as_view(), name="arrival_drink"),
    path('arrivals/delete', views.ArrivalDeleteView.as_view(), name="arrival_delete"),

    path('employee', views.EmployeeView.as_view(), name="employee"),

    path('inventory/bar', views.InventoryBarView.as_view(), name="inventory_bar"),
    path('inventory/ware', views.InventoryWareView.as_view(), name="inventory_ware"),

    path('malfunctions', views.MalfunctionsView.as_view(), name="malfunctions"),
    path('malfunctions/complete', views.MalfunctionCompleteView.as_view(), name="malfunction_complete"),

    path('fines', views.FinesView.as_view(), name="fines"),

    path('data_logs/timetable', views.TimetableDataLogView.as_view(), name="data_log_timetable"),
    path('data_logs/arrivals', views.ArrivalsDataLogView.as_view(), name="data_log_arrivals"),
    path('data_logs/end_day', views.EndDayDataLogView.as_view(), name="data_log_end_day"),

    path('need_items', views.NeedItemsView.as_view(), name="need_items"),
    path('need_items/receive', views.NeedItemsReceiveView.as_view(), name="receive_need_item"),

    path('revise', views.SendReviseMessageView.as_view(), name="revise"),

    path('end_day', views.EndDayView.as_view(), name="end_day"),

    path('faq', views.FAQBarView.as_view(), name='bar_faq')
]

app/apps/lk/urls.py
from django.urls import path

from .views import *

app_name = 'LK'

urlpatterns = [
    path('', IndexView.as_view(), name="index"),

    path('catalog', CatalogView.as_view(), name="catalog"),
    path('catalog/add', CatalogCreateView.as_view(), name="catalog_add"),
    path('catalog/edit', CatalogEditView.as_view(), name="catalog_edit"),
    path('catalog/delete', CatalogDeleteView.as_view(), name="catalog_delete"),

    path('catalog/type/add', CatalogTypeCreateView.as_view(), name="catalog_type_add"),
    path('catalog/types/edit', CatalogTypeEditView.as_view(), name="catalog_type_edit"),
    path('catalog/types/delete', CatalogTypeDeleteView.as_view(), name="catalog_type_delete"),

    path('bars', BarsView.as_view(), name="bars"),
    path('bars/settings', BarSettingsView.as_view(), name="bars_settings"),
    path('product_remains_add', product_remains_add, name="product_remains_add"),
    path('link_question_to_bar_setting', link_question_to_bar_setting, name="link_question_to_bar_setting"),

    path('positions', PositionsView.as_view(), name="positions"),
    path('positions/edit', PositionsEditView.as_view(), name="position_edit"),
    path('positions/delete', PositionDeleteView.as_view(), name="position_delete"),

    path('jobs/add', JobAddView.as_view(), name="job_add"),

    path('bank', BankView.as_view(), name="bank"),
    path('bank/update', bank_update, name="update_bank"),
    path('bank/partners', BankPartnersView.as_view(), name="bank_partners"),
    path('bank/partners/edit', BankPartnerEditView.as_view(), name="edit_bank_partner"),
    path('bank/cards', BankCardsView.as_view(), name="bank_cards"),
    path('bank/cards/create', BankCardCreateView.as_view(), name="create_bank_card"),
    path('bank/cards/edit', BankCardEditView.as_view(), name="edit_bank_card"),

    path('money', MoneyView.as_view(), name="money"),
    path('money/update', update_money, name="update_money"),
    path('money/edit', MoneyEditView.as_view(), name="edit_money"),
    path('money/update_all', update_all_money_and_sessions, name="update_all_money"),
    path('money/differences', MoneyDifferencesView.as_view(), name="money_differences"),

    path('timetable', TimetableView.as_view(), name="timetable"),
    path('timetable/create', CreateTimetableView.as_view(), name="create_timetable"),
    path('timetable/edit', EditTimetableView.as_view(), name="edit_timetable"),
    path('timetable/delete', DeleteTimetableView.as_view(), name="delete_timetable"),
    path('timetable/update', TimetableUpdateView.as_view(), name="update_timetable"),

    path('expenses', ExpensesView.as_view(), name="expenses"),
    path('expenses/create', CreateExpenseView.as_view(), name="create_expense"),
    path('expenses/edit', EditExpenseView.as_view(), name="edit_expense"),
    path('expenses/delete', DeleteExpenseView.as_view(), name="delete_expense"),
    path('expenses/status', ExpenseStatusView.as_view(), name="status_expense"),

    path('salary', SalaryView.as_view(), name="salary"),
    path('salary/create', CreateSalaryView.as_view(), name="create_salary"),
    path('salary/edit', EditSalaryView.as_view(), name="edit_salary"),
    path('salary/delete', DeleteSalaryView.as_view(), name="delete_salary"),

    path('pays', PaysView.as_view(), name="pays"),
    path('pays/create', CreatePaysView.as_view(), name="create_pays"),
    path('pays/edit', EditPaysView.as_view(), name="edit_pays"),
    path('pays/delete', DeletePaysView.as_view(), name="delete_pays"),

    path('fines', FinesView.as_view(), name="fines"),
    path('fines/create', CreateFineView.as_view(), name="create_fine"),
    path('fines/edit', EditFinesView.as_view(), name="edit_fine"),
    path('fines/delete', DeleteFineView.as_view(), name="delete_fine"),

    path('employees', EmployeesView.as_view(), name="employees"),
    path('employees/create', CreateEmployeeView.as_view(), name="create_employee"),
    path('employees/edit', EditEmployeeView.as_view(), name="edit_employee"),
    path('employees/dismiss', DissmissEmployeeView.as_view(), name="dismiss_employee"),
    path('employees/return', ReturnToWorkEmployeeView.as_view(), name="return_employee"),

    path('tovar/arrivals', ArrivalsView.as_view(), name="tovar_arrivals"),
    path('tovar/arrivals/create', ArrivalCreateView.as_view(), name="tovar_arrival_create"),
    path('tovar/arrivals/edit', ArrivalEditView.as_view(), name="tovar_arrival_edit"),
    path('tovar/arrivals/delete', ArrivalDeleteView.as_view(), name="tovar_arrival_delete"),
    path('tovar/arrivals/invoices', ArrivalInvoicesView.as_view(), name="total_arrival_invoices"),
    path('tovar/arrivals/invoices/all', ArrivalInvoicesAllView.as_view()),
    path('tovar/requests', TovarRequestsView.as_view(), name="tovar_requests"),
    path('tovar/requests/edit', TovarRequestEditView.as_view(), name="tovar_request_edit"),
    path('tovar/requests/delete', TovarRequestDeleteView.as_view(), name="tovar_request_delete"),

    path('need_items', ItemDeficitView.as_view(), name="need_items"),
    path('need_items/create', NeedItemsCreateView.as_view(), name="need_items_create"),
    path('need_items/send', ItemDeficitSendView.as_view(), name="receive_need_item"),

    path('bars/actions', BarActionsView.as_view()),
    path('send_message_on_bar', SendMessageOnBar.as_view(), name="send_message_on_bar"),

    path('malfunctions', MalfunctionsView.as_view(), name="malfunctions"),
    path('malfunctions/create', MalfunctionCreateView.as_view(), name="malfunction_create"),
    path('malfunctions/delete', MalfunctionDeleteView.as_view(), name="malfunction_delete"),
    path('malfunctions/complete', MalfunctionCompleteView.as_view()),

    path('reviews', ReviewsView.as_view(), name="reviews"),
    path('reviews/create', review_create, name="review_create"),
    path('reviews/link_to_employee', review_link_to_employee, name="review_to_employee"),
  
    path('logs', LogsView.as_view(), name="logs"),
    path('logs/update', update_logs_view, name="update_logs"),
    path('logs/filter', LogsWithFilterView.as_view(), name="logs_with_filter"),

    path('purchaser', PurchaserView.as_view(), name='purchaser'),
    path('purchaser_get_table', get_table_for_purchaser, name='purchaser_get_table'),

    path('reports', ReportsView.as_view()),
    path('reports/money/update', ReportsMoneyUpdateView.as_view()),
    path('reports/expense_types_by_storage', ReportExpenseTypesByStorageView.as_view()),

    path('faq', FAQView.as_view(), name='faq'),
    path('faq/create', FAQCreateView.as_view(), name='create_faq'),
    path('faq/edit', FAQEditView.as_view(), name='edit_faq'),
    path('faq/delete', FAQDeleteView.as_view(), name='delete_faq'),
    path('faq/tags/create', FAQTagCreateView.as_view(), name='create_faq_tag'),
    path('faq/tags/edit', FAQTagEditView.as_view(), name='edit_faq_tag'),
    path('faq/tags/delete', FAQTagDeleteView.as_view(), name='delete_faq_tag')
]

app/config/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('', lambda x: redirect(settings.LOGIN_REDIRECT_URL)),

    path('lk/', include('apps.lk.urls')),
    path('iiko/', include('apps.iiko.urls')),
    path('bar/', include('apps.bar.urls')),
    path('repairer/', include('apps.repairer.urls')),
    path('api/', include('apps.api.urls')),
    path('purchaser/', include('apps.purchaser.urls')),
    path('admin/', include('apps.admin.urls')),
    path('brand_chief/', include('apps.brand_chief.urls')),

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
        re_path(r'^assets/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
    ]

app/apps/api/views/bar_views.py
from apps.bar.models import Pays, Arrival, TovarRequest, Timetable, Salary, Money, ArrivalKeg, ArrivalInvoice
from ..serializers import MoneySerializer, SalarySerializer, TimetableSerializer, TovarRequestSerializer, \
    ArrivalSerializer, PaysSerializer, ArrivalKegSerializer, ArrivalInvoiceSerializer
from ..mixins import ModelViewSetMixin


class MoneyViewSet(ModelViewSetMixin):
    queryset = Money.objects.all()
    serializer_class = MoneySerializer


class SalaryViewSet(ModelViewSetMixin):
    queryset = Salary.objects.all()
    serializer_class = SalarySerializer


class TimetableViewSet(ModelViewSetMixin):
    queryset = Timetable.objects.all()
    serializer_class = TimetableSerializer


class TovarRequestViewSet(ModelViewSetMixin):
    queryset = TovarRequest.objects.all()
    serializer_class = TovarRequestSerializer


class ArrivalViewSet(ModelViewSetMixin):
    queryset = Arrival.objects.all()
    serializer_class = ArrivalSerializer


class ArrivalKegViewSet(ModelViewSetMixin):
    queryset = ArrivalKeg.objects.all()
    serializer_class = ArrivalKegSerializer


class PaysViewSet(ModelViewSetMixin):
    queryset = Pays.objects.all()
    serializer_class = PaysSerializer


class ArrivalInvoiceViewSet(ModelViewSetMixin):
    queryset = ArrivalInvoice.objects.all()
    serializer_class = ArrivalInvoiceSerializer

app/apps/api/views/lk_views.py
from rest_framework.viewsets import ModelViewSet

from apps.api.serializers import NavbarSerializer, RoleSerializer, ProfileSerializer, JobPlaceSerializer, \
    PositionSerializer, \
    EmployeeSerializer, CatalogTypeSerializer, CatalogSerializer, TestQuestionSerializer, TestSerializer, \
    TestResultSerializer, TelegramChatSerializer, CardSerializer, PartnerSerializer, StatementSerializer, \
    FineSerializer, ExpenseSerializer, LogsSerializer, ItemDeficitSerializer, MalfunctionSerializer, ReviewSerializer, \
    FAQSerializer, FAQTagSerializer
from apps.api.mixins import ModelViewSetMixin

from apps.lk.models import Navbar, Role, Profile, JobPlace, Position, Employee, Catalog, CatalogType, Log, Expense, \
    Fine, Statement, Card, Partner, TelegramChat, TestResult, Test, TestQuestion, ItemDeficit, Review, FAQ, FAQTag
from apps.repairer.models import Malfunction


class NavbarViewSet(ModelViewSetMixin):
    queryset = Navbar.objects.all()
    serializer_class = NavbarSerializer


class RoleViewSet(ModelViewSetMixin):
    queryset = Role.objects.all()
    serializer_class = RoleSerializer


class ProfileViewSet(ModelViewSetMixin):
    queryset = Profile.objects.all()
    serializer_class = ProfileSerializer


class JobPlaceViewSet(ModelViewSetMixin):
    queryset = JobPlace.objects.all()
    serializer_class = JobPlaceSerializer


class PositionViewSet(ModelViewSetMixin):
    queryset = Position.objects.all()
    serializer_class = PositionSerializer


class EmployeeViewSet(ModelViewSetMixin):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer

    def get_queryset(self):
        is_deleted = self.request.query_params.get('is_deleted')

        if is_deleted:
            return Employee.objects.filter(is_deleted=int(is_deleted))
        else:
            return Employee.objects.all()


class CatalogTypeViewSet(ModelViewSetMixin):
    queryset = CatalogType.objects.all()
    serializer_class = CatalogTypeSerializer


class CatalogViewSet(ModelViewSetMixin):
    queryset = Catalog.objects.all()
    serializer_class = CatalogSerializer


class TestQuestionViewSet(ModelViewSetMixin):
    queryset = TestQuestion.objects.all()
    serializer_class = TestQuestionSerializer


class TestViewSet(ModelViewSetMixin):
    queryset = Test.objects.all()
    serializer_class = TestSerializer


class TestResultViewSet(ModelViewSetMixin):
    queryset = TestResult.objects.all()
    serializer_class = TestResultSerializer


class TelegramChatViewSet(ModelViewSetMixin):
    queryset = TelegramChat.objects.all()
    serializer_class = TelegramChatSerializer


class PartnerViewSet(ModelViewSetMixin):
    queryset = Partner.objects.all()
    serializer_class = PartnerSerializer


class CardViewSet(ModelViewSetMixin):
    queryset = Card.objects.all()
    serializer_class = CardSerializer


class StatementViewSet(ModelViewSetMixin):
    queryset = Statement.objects.all()
    serializer_class = StatementSerializer


class FineViewSet(ModelViewSetMixin):
    queryset = Fine.objects.all()
    serializer_class = FineSerializer


class ExpenseViewSet(ModelViewSetMixin):
    queryset = Expense.objects.all()
    serializer_class = ExpenseSerializer


class LogsViewSet(ModelViewSetMixin):
    queryset = Log.objects.all()
    serializer_class = LogsSerializer


class ItemDeficitViewSet(ModelViewSetMixin):
    queryset = ItemDeficit.objects.all()
    serializer_class = ItemDeficitSerializer

    def get_queryset(self):
        without_success = self.request.query_params.get('without_success')

        if without_success and without_success == '1':
            return ItemDeficit.objects.exclude(status=3)
        else:
            return ItemDeficit.objects.filter(status=3)


class MalfunctionViewSet(ModelViewSetMixin):
    queryset = Malfunction.objects.all()
    serializer_class = MalfunctionSerializer


class ReviewViewSet(ModelViewSetMixin):
    queryset = Review.objects.all()
    serializer_class = ReviewSerializer


class FAQViewSet(ModelViewSet):
    queryset = FAQ.objects.all()
    serializer_class = FAQSerializer


class FAQTagViewSet(ModelViewSet):
    queryset = FAQTag.objects.all()
    serializer_class = FAQTagSerializer

app/templates/lk/bank.html
{% extends 'base.html' %}

{% block title %}Банковские выписки{% endblock %}
{% block page_title %}Банковские выписки{% endblock %}

{% block css %}
    <link rel="stylesheet" href="/assets/libs/dropzone/dist/dropzone.css">
{% endblock %}

{% block body %}
    <div class="container-xl">
        <div class="mb-2">
            <div class="card rounded-3">
                <div class="card-header card-header-light rounded-top-3"><h3 class="card-title">Загрузка выписки</h3>
                </div>
                <div class="card-body">
                    <form class="dropzone" id="myDropzone" action="{% url 'LK:update_bank' %}">
                        {% csrf_token %}
                        <div class="fallback">
                            <input name="file" type="file"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="card rounded-3">
            <div class="card-header card-header-light rounded-top-3">
                <h3 class="card-title">Банковские выписки</h3>
                <div class="card-actions">
                    <div class="row">
                        <div class="col-6">
                            <a href="{% url 'LK:bank_partners' %}" class="btn btn-tabler">
                                Контрагенты
                            </a>
                        </div>
                        <div class="col-6 gx-4">
                            <a href="{% url 'LK:bank_cards' %}" class="btn btn-tabler">
                                Карты
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-sm table-striped table-hover table-bordered nowrap w-100"
                           id="bank-table">
                        <thead>
                        <tr class="column-filter dt-column-filter">
                            <th><input type="text" class="form-control form-control-sm" placeholder=""></th>
                            <th><input type="text" class="form-control form-control-sm" placeholder=""></th>
                            <th><input type="text" class="form-control form-control-sm" placeholder=""></th>
                            <th><input type="text" class="form-control form-control-sm" placeholder=""></th>
                            <th><input type="text" class="form-control form-control-sm" placeholder=""></th>
                            <th><input type="text" class="form-control form-control-sm" placeholder=""></th>
                            <th><input type="text" class="form-control form-control-sm" placeholder=""></th>
                            <th><input type="text" class="form-control form-control-sm" placeholder=""></th>
                            <th><input type="text" class="form-control form-control-sm" placeholder=""></th>
                            <th><input type="text" class="form-control form-control-sm" placeholder=""></th>
                            <th></th>
                        </tr>
                        <tr>
                            <th>Привязка</th>
                            <th>Номер</th>
                            <th>Дата</th>
                            <th>Дата списано</th>
                            <th>Дата поступило</th>
                            <th>Сумма</th>
                            <th>Плательщик</th>
                            <th>Получатель</th>
                            <th>Назначение платежа</th>
                            <th>Тип документа</th>
                            <th></th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="/assets/libs/dropzone/dist/dropzone-min.js"></script>
    <script>
        let bank_table = run_datatable('bank-table', '/api/statement', '/lk/bank', [
            {data: 'linked'},
            {data: 'document_number'},
            {data: 'date'},
            {data: 'date_write_off'},
            {data: 'date_receipt'},
            {data: 'sum'},
            {data: 'payer_name'},
            {data: 'recipient_name'},
            {data: 'payment_purpose'},
            {data: 'document_type'}
        ])
        let myDropzone = new Dropzone('#myDropzone', {})
        myDropzone.on("complete", file => {
            bank_table.destroy()
            bank_table = run_datatable('bank-table', '/api/statement', '/lk/bank', [
                {data: 'linked'},
                {data: 'document_number'},
                {data: 'date'},
                {data: 'date_write_off'},
                {data: 'date_receipt'},
                {data: 'sum'},
                {data: 'payer_name'},
                {data: 'recipient_name'},
                {data: 'payment_purpose'},
                {data: 'document_type'}
            ])
            notification(true, 'Банковская выписка успешно загружена :)')
        });
    </script>
{% endblock %}

app/templates/lk/bars_settings.html
{% extends 'base.html' %}

{% block title %}Настройки заведений{% endblock %}
{% block page_title %}Настройки заведения {{ row.storage.name }}{% endblock %}

{% block body %}
    <div class="container-xl">
        <div class="card rounded-3">
            <!-- Cards navigation -->
            <div class="card-header">
                <ul class="nav nav-tabs card-header-tabs nav-fill">
                    <li class="nav-item"><a href="#tab-top-1" id="btn-tab-top-1" class="tab-top nav-link active"
                                            data-bs-toggle="tab">Настройка параметров</a></li>
                    <li class="nav-item"><a href="#tab-top-2" id="btn-tab-top-2" class="tab-top nav-link"
                                            data-bs-toggle="tab">Вопросы</a></li>
                    <li class="nav-item"><a href="#tab-top-3" id="btn-tab-top-3" class="tab-top nav-link"
                                            data-bs-toggle="tab">Посуда</a></li>
                </ul>
            </div>
            <div class="tab-content">
                <!-- Content of card #1 -->
                <div id="tab-top-1" class="card tab-pane active show">
                    <div class="card-body">
                        <div class="card-title mb-2">Настройка параметров</div>
                        <form action="{% url 'LK:bars_settings' %}?id={{ row.id }}" method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label class="form-label">Процент</label>
                                <input class="form-control" name="percent" placeholder="Введите процент для барменов"
                                       value="{{ row.percent }}">
                            </div>
                            <div class="mb-3">
                                <label class="form-label">ID телеграм чата заведения</label>
                                <input class="form-control" name="tg_chat_id"
                                       placeholder="Введите ID телеграм чата заведения"
                                       value="{% if row.tg_chat_id %}{{ row.tg_chat_id }}{% endif %}">
                            </div>
                            <div class="mb-2">
                                <button type="submit" class="btn bg-dark-lt w-100">Сохранить</button>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- Content of card #2 -->
                <div id="tab-top-2" class="card tab-pane">
                    <div class="card-body">
                        <div class="card-title">Вопросы на конце дня</div>
                        <table class="table table-sm table-bordered table-striped table-hover nowrap w-100 mb-4">
                            <thead>
                            <tr>
                                <th>Сообщение</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for question in row.end_day_questions.all %}
                                <tr>
                                    <td>{{ question.text }}</td>
                                    <td></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <form action="{% url 'LK:link_question_to_bar_setting' %}?id={{ row.id }}" method="post">
                            {% csrf_token %}
                            <div class="mb-1">
                                <label class="form-label">Существующие вопросы</label>
                                <select class="form-select" placeholder="Выберите вопрос из существующих"
                                        name="question_id">
                                    <option></option>
                                    {% for question in questions %}
                                        {% if question not in row.end_day_questions.all %}
                                            <option value="{{ question.id }}">{{ question.text }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                            <p class="text-muted mb-1">или</p>
                            <div class="mb-3">
                                <label class="form-label">Новый вопрос</label>
                                <input class="form-control" name="question_text"
                                       placeholder="Введите текст нового вопроса">
                            </div>
                            <div class="mb-2">
                                <button type="submit" class="btn bg-dark-lt w-100">Сохранить</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div id="tab-top-3" class="card tab-pane">
                    <div class="card-body">
                        <div class="card-title mb-2">Минимальное количество посуды</div>
                        <form action="{% url 'LK:product_remains_add' %}?id={{ row.id }}" method="post">
                            {% csrf_token %}
                            <div class="mb-4">
                                <div class="columns-4 gap-4">
                                    {% for product in products %}
                                        <div class="row mb-1">
                                            <div class="col-6">{{ product.name }}</div>
                                            <div class="col-5"><input class="form-control"
                                                                      name="{{ product.id }}"
                                                                      placeholder="Остаток"
                                                                      {% for remain in remains %}
                                                                          {% if remain.product.id == product.id %}
                                                                              value="{{ remain.amount }}"
                                                                          {% endif %}
                                                                      {% endfor %}
                                                               ></div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="mb-2">
                                <button type="submit" class="btn w-100">Сохранить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal modal-blur fade" id="how-to-chat-id" tabindex="-1" aria-hidden="true"
         style="display: none;">
        <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
            <div class="modal-content">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                <div class="modal-status bg-primary"></div>
                <div class="modal-body text-center py-4">
                    <!-- Download SVG icon from http://tabler-icons.io/i/circle-check -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon mb-2 text-primary icon-lg" width="24"
                         height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                         stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                        <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path>
                        <path d="M12 8l.01 0"></path>
                        <path d="M11 12l1 0l0 4l1 0"></path>
                    </svg>
                    <h3>Как получить ID чата?</h3>
                    <div class="text-muted">Создайте беседу с Вами и ботом, который привязан к Вашему приложению.
                        Затем
                        отправьте в эту беседу команду: <b>/get_chat_id</b> и вставьте полученные цифры в сообщении
                        в
                        поле для ввода ниже.<br>
                        <b>Фото инструкция:</b></div>
                </div>
                <div class="modal-footer">
                    <div class="w-100">
                        <div class="row">
                            <div class="col"><a href="#" class="btn btn-primary w-100" data-bs-dismiss="modal">
                                ОК
                            </a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
            let first_tab = $('#btn-tab-top-1')
            let second_tab = $('#btn-tab-top-2')
            let third_tab = $('#btn-tab-top-3')
            first_tab.click(function () {
                $('.tab-top').removeClass('active')
                first_tab.addClass('active')
            })
            second_tab.click(function () {
                $('.tab-top').removeClass('active')
                second_tab.addClass('active')
            })
            third_tab.click(function () {
                $('.tab-top').removeClass('active')
                second_tab.addClass('active')
            })
        })
    </script>
{% endblock %}