app/apps/lk/urls.py
from django.urls import path

from .views import *

app_name = 'LK'

urlpatterns = [
    path('', IndexView.as_view(), name="index"),

    path('catalog', CatalogView.as_view(), name="catalog"),
    path('catalog/add', CatalogCreateView.as_view(), name="catalog_add"),
    path('catalog/edit', CatalogEditView.as_view(), name="catalog_edit"),
    path('catalog/delete', CatalogDeleteView.as_view(), name="catalog_delete"),

    path('catalog/type/add', CatalogTypeCreateView.as_view(), name="catalog_type_add"),
    path('catalog/types/edit', CatalogTypeEditView.as_view(), name="catalog_type_edit"),
    path('catalog/types/delete', CatalogTypeDeleteView.as_view(), name="catalog_type_delete"),

    path('bars', BarsView.as_view(), name="bars"),
    path('bars/settings', BarSettingsView.as_view(), name="bars_settings"),
    path('product_remains_add', product_remains_add, name="product_remains_add"),
    path('link_question_to_bar_setting', link_question_to_bar_setting, name="link_question_to_bar_setting"),

    path('positions', PositionsView.as_view(), name="positions"),
    path('positions/edit', PositionsEditView.as_view(), name="position_edit"),
    path('positions/delete', PositionDeleteView.as_view(), name="position_delete"),

    path('jobs/add', JobAddView.as_view(), name="job_add"),

    path('bank', BankView.as_view(), name="bank"),
    path('bank/update', bank_update, name="update_bank"),
    path('bank/partners', BankPartnersView.as_view(), name="bank_partners"),
    path('bank/partners/edit', BankPartnerEditView.as_view(), name="edit_bank_partner"),
    path('bank/cards', BankCardsView.as_view(), name="bank_cards"),
    path('bank/cards/create', BankCardCreateView.as_view(), name="create_bank_card"),
    path('bank/cards/edit', BankCardEditView.as_view(), name="edit_bank_card"),

    path('money', MoneyView.as_view(), name="money"),
    path('money/update', update_money, name="update_money"),
    path('money/edit', MoneyEditView.as_view(), name="edit_money"),
    path('money/update_all', update_all_money_and_sessions, name="update_all_money"),
    path('money/differences', MoneyDifferencesView.as_view(), name="money_differences"),

    path('timetable', TimetableView.as_view(), name="timetable"),
    path('timetable/create', CreateTimetableView.as_view(), name="create_timetable"),
    path('timetable/edit', EditTimetableView.as_view(), name="edit_timetable"),
    path('timetable/delete', DeleteTimetableView.as_view(), name="delete_timetable"),
    path('timetable/update', TimetableUpdateView.as_view(), name="update_timetable"),

    path('expenses', ExpensesView.as_view(), name="expenses"),
    path('expenses/create', CreateExpenseView.as_view(), name="create_expense"),
    path('expenses/edit', EditExpenseView.as_view(), name="edit_expense"),
    path('expenses/delete', DeleteExpenseView.as_view(), name="delete_expense"),
    path('expenses/status', ExpenseStatusView.as_view(), name="status_expense"),

    path('salary', SalaryView.as_view(), name="salary"),
    path('salary/create', CreateSalaryView.as_view(), name="create_salary"),
    path('salary/edit', EditSalaryView.as_view(), name="edit_salary"),
    path('salary/delete', DeleteSalaryView.as_view(), name="delete_salary"),

    path('pays', PaysView.as_view(), name="pays"),
    path('pays/create', CreatePaysView.as_view(), name="create_pays"),
    path('pays/edit', EditPaysView.as_view(), name="edit_pays"),
    path('pays/delete', DeletePaysView.as_view(), name="delete_pays"),

    path('fines', FinesView.as_view(), name="fines"),
    path('fines/create', CreateFineView.as_view(), name="create_fine"),
    path('fines/edit', EditFinesView.as_view(), name="edit_fine"),
    path('fines/delete', DeleteFineView.as_view(), name="delete_fine"),

    path('employees', EmployeesView.as_view(), name="employees"),
    path('employees/create', CreateEmployeeView.as_view(), name="create_employee"),
    path('employees/edit', EditEmployeeView.as_view(), name="edit_employee"),
    path('employees/dismiss', DissmissEmployeeView.as_view(), name="dismiss_employee"),
    path('employees/return', ReturnToWorkEmployeeView.as_view(), name="return_employee"),

    path('tovar/arrivals', ArrivalsView.as_view(), name="tovar_arrivals"),
    path('tovar/arrivals/create', ArrivalCreateView.as_view(), name="tovar_arrival_create"),
    path('tovar/arrivals/edit', ArrivalEditView.as_view(), name="tovar_arrival_edit"),
    path('tovar/arrivals/delete', ArrivalDeleteView.as_view(), name="tovar_arrival_delete"),
    path('tovar/arrivals/invoices', ArrivalInvoicesView.as_view(), name="total_arrival_invoices"),
    path('tovar/arrivals/invoices/all', ArrivalInvoicesAllView.as_view()),
    path('tovar/requests', TovarRequestsView.as_view(), name="tovar_requests"),
    path('tovar/requests/edit', TovarRequestEditView.as_view(), name="tovar_request_edit"),
    path('tovar/requests/delete', TovarRequestDeleteView.as_view(), name="tovar_request_delete"),

    path('need_items', ItemDeficitView.as_view(), name="need_items"),
    path('need_items/create', NeedItemsCreateView.as_view(), name="need_items_create"),
    path('need_items/send', ItemDeficitSendView.as_view(), name="receive_need_item"),

    path('bars/actions', BarActionsView.as_view()),
    path('send_message_on_bar', SendMessageOnBar.as_view(), name="send_message_on_bar"),

    path('malfunctions', MalfunctionsView.as_view(), name="malfunctions"),
    path('malfunctions/create', MalfunctionCreateView.as_view(), name="malfunction_create"),
    path('malfunctions/delete', MalfunctionDeleteView.as_view(), name="malfunction_delete"),
    path('malfunctions/complete', MalfunctionCompleteView.as_view()),

    path('reviews', ReviewsView.as_view(), name="reviews"),
    path('reviews/create', review_create, name="review_create"),
    path('reviews/link_to_employee', review_link_to_employee, name="review_to_employee"),
  
    path('logs', LogsView.as_view(), name="logs"),
    path('logs/update', update_logs_view, name="update_logs"),
    path('logs/filter', LogsWithFilterView.as_view(), name="logs_with_filter"),

    path('purchaser', PurchaserView.as_view(), name='purchaser'),
    path('purchaser_get_table', get_table_for_purchaser, name='purchaser_get_table'),

    path('reports', ReportsView.as_view()),
    path('reports/money/update', ReportsMoneyUpdateView.as_view()),
    path('reports/expense_types_by_storage', ReportExpenseTypesByStorageView.as_view()),

    path('faq', FAQView.as_view(), name='faq'),
    path('faq/create', FAQCreateView.as_view(), name='create_faq'),
    path('faq/edit', FAQEditView.as_view(), name='edit_faq'),
    path('faq/delete', FAQDeleteView.as_view(), name='delete_faq'),
    path('faq/tags/create', FAQTagCreateView.as_view(), name='create_faq_tag'),
    path('faq/tags/edit', FAQTagEditView.as_view(), name='edit_faq_tag'),
    path('faq/tags/delete', FAQTagDeleteView.as_view(), name='delete_faq_tag')
]

app/config/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('', lambda x: redirect(settings.LOGIN_REDIRECT_URL)),

    path('lk/', include('apps.lk.urls')),
    path('iiko/', include('apps.iiko.urls')),
    path('bar/', include('apps.bar.urls')),
    path('repairer/', include('apps.repairer.urls')),
    path('api/', include('apps.api.urls')),
    path('purchaser/', include('apps.purchaser.urls')),
    path('admin/', include('apps.admin.urls')),
    path('brand_chief/', include('apps.brand_chief.urls')),

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
        re_path(r'^assets/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
    ]

app/apps/lk/models/models.py
from django.db import models
from django.contrib.auth.models import User

from . import managers

from apps.iiko.models import Storage, Product


class Navbar(models.Model):
    link = models.CharField(max_length=64)
    text = models.CharField(max_length=64)
    app_name = models.CharField(max_length=16)


class Role(models.Model):
    name = models.CharField(max_length=32)
    can_all = models.BooleanField(default=False)
    can_create = models.BooleanField(default=False)
    can_edit = models.BooleanField(default=False)
    can_delete = models.BooleanField(default=False)
    can_view = models.ManyToManyField(Navbar)

    objects = managers.RoleManager()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.ForeignKey(to=Role, on_delete=models.SET_NULL, null=True)
    tg_id = models.CharField(max_length=32, null=True)

    objects = managers.ProfileManager()


class JobPlace(models.Model):
    name = models.CharField(max_length=32)
    main_shift_oklad_accrual = models.IntegerField(default=0)
    gain_shift_oklad_accrual = models.IntegerField(default=0)
    main_shift_oklad_receiving = models.IntegerField(default=0)
    gain_shift_oklad_receiving = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Position(models.Model):
    name = models.CharField(max_length=32)
    args = models.JSONField(null=True)
    linked_jobs = models.ManyToManyField(JobPlace)
    priority_id = models.IntegerField()

    objects = managers.PositionManager()
    
    
class Review(models.Model):
    STATUS_CHOICES = [
        (1, 'Создан'),
        (2, 'Закрыт')
    ]
    
    created_at = models.DateField(auto_now_add=True)
    review_date = models.DateField()
    storage = models.ForeignKey(to=Storage, on_delete=models.CASCADE)
    jobs = models.ManyToManyField(to=JobPlace)
    photo = models.ImageField(upload_to='reviews_photo')
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES, default=1)

    objects = managers.ReviewManager()


class Employee(models.Model):
    STATUS_CHOICES = [
        (1, 'Кандидат'),
        (2, 'Стажер'),
        (3, 'Сотрудник'),
        (4, 'Резерв')
    ]

    code = models.CharField(max_length=64)
    photo = models.ImageField(upload_to='employee_photo', null=True)
    fio = models.CharField(max_length=64)
    birth_date = models.DateField(null=True)
    address = models.CharField(max_length=64, null=True)
    job_place = models.ForeignKey(JobPlace, on_delete=models.SET_NULL, null=True)
    storage = models.ForeignKey(Storage, on_delete=models.SET_NULL, null=True)
    phone = models.CharField(max_length=11)
    is_deleted = models.PositiveSmallIntegerField(default=0)
    dismiss_date = models.DateField(null=True)
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES, default=3)
    reviews = models.ManyToManyField(to=Review)

    objects = managers.EmployeeManager()

    def get_status_by_id(self, status_id: int) -> str:
        return next(item[1] for item in self.STATUS_CHOICES if item[0] == status_id)


class EmployeeLog(models.Model):
    TYPE_CHOICES = [
        (1, 'Увольнение'),
        (2, 'Восстановление'),
        (3, 'Смена статуса'),
        (4, 'Описание')
    ]

    date_at = models.DateField()
    employee = models.ForeignKey(to=Employee, on_delete=models.CASCADE)
    type = models.PositiveSmallIntegerField(choices=TYPE_CHOICES)
    comment = models.CharField(max_length=255)

    objects = managers.EmployeeLogManager()


class CatalogType(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name


class Catalog(models.Model):
    name = models.CharField(max_length=32)
    catalog_types = models.ManyToManyField(CatalogType)
    args = models.JSONField(default=dict)

    objects = managers.CatalogManager()


class TestQuestion(models.Model):
    text = models.CharField(max_length=128)
    is_correct = models.PositiveSmallIntegerField()


class Test(models.Model):
    created_at = models.DateField()
    name = models.CharField(max_length=32)
    questions = models.ManyToManyField(TestQuestion)
    is_ended = models.PositiveSmallIntegerField()

    objects = managers.TestManager()


class TestResult(models.Model):
    created_at = models.DateTimeField(auto_now=True)
    test = models.ForeignKey(Test, on_delete=models.SET_NULL, null=True)
    employee = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True)
    correct_answers = models.IntegerField()
    logs = models.JSONField()

    objects = managers.TestResultManager()


class TelegramChat(models.Model):
    chat_id = models.CharField(max_length=16)
    name = models.CharField(max_length=32)


class Partner(models.Model):
    name = models.CharField(max_length=128)
    inn = models.CharField(max_length=12)
    friendly_name = models.CharField(max_length=64)
    expense_types = models.ManyToManyField(Catalog)
    storages = models.ManyToManyField(Storage)

    objects = managers.PartnerManager()


class Card(models.Model):
    name = models.CharField(max_length=32)
    num = models.CharField(max_length=16)
    storage = models.ForeignKey(Storage, on_delete=models.SET_NULL, null=True)
    type = models.IntegerField()

    objects = managers.CardManager()


class Statement(models.Model):
    linked = models.ForeignKey(Card, on_delete=models.SET_NULL, null=True)
    document_type = models.CharField(max_length=32)
    document_number = models.IntegerField()
    date = models.DateField(null=True)
    date_write_off = models.DateField(null=True)
    date_receipt = models.DateField(null=True)
    sum = models.FloatField()
    payer = models.ForeignKey(Partner, on_delete=models.SET_NULL, null=True, related_name='payer')
    recipient = models.ForeignKey(Partner, on_delete=models.SET_NULL, null=True, related_name='recipient')
    payment_purpose = models.CharField(max_length=256)
    comment = models.CharField(max_length=64, null=True)

    objects = managers.StatementManager()


class Fine(models.Model):
    created_at = models.DateTimeField(auto_now=True)
    date_at = models.DateField()
    employee = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True)
    sum = models.IntegerField()
    reason = models.ForeignKey(Catalog, on_delete=models.SET_NULL, null=True)
    is_received = models.PositiveSmallIntegerField(default=0)

    objects = managers.FineManager()


class Expense(models.Model):
    writer = models.CharField(max_length=32)
    date_at = models.DateField()
    created_at = models.DateTimeField(auto_now=True)
    storage = models.ForeignKey(Storage, on_delete=models.SET_NULL, null=True)
    expense_type = models.ForeignKey(Catalog, on_delete=models.SET_NULL, null=True, related_name='type')
    expense_source = models.ForeignKey(Catalog, on_delete=models.SET_NULL, null=True, related_name='source')
    payment_receiver = models.CharField(max_length=64, null=True)
    sum = models.FloatField()
    comment = models.CharField(max_length=128)

    objects = managers.ExpenseManager()


class Log(models.Model):
    """
        Example:
            created_at = 2023-06-07 12:20:35
            owner = CRM Гаражная 83/1 | admin | some_user_name
            entity = Иван Иванов
            row = Timetable 12 | Expense 14
            action = 1
            additional_data = Вышел на смену | Получил зарплату за Апрель с 1 по 15 число
    """

    ACTION_CHOICES = [
        (1, 'Создание записи'),
        (2, 'Редактирование записи'),
        (3, 'Удаление записи'),
        (4, 'Обновление записи'),
        (5, 'Копирование записи')
    ]

    created_at = models.DateTimeField(auto_now_add=True)
    owner = models.CharField(max_length=255)
    entity = models.CharField(max_length=255)
    row = models.CharField(max_length=255)
    action = models.PositiveIntegerField(choices=ACTION_CHOICES)
    additional_data = models.CharField(max_length=255)


class ItemDeficit(models.Model):
    STATUS_CHOICES = [
        (1, 'Создано'),
        (2, 'Отправлено'),
        (3, 'Получено')
    ]

    created_at = models.DateTimeField()
    owner = models.ForeignKey(to=Profile, on_delete=models.SET_NULL, null=True)
    storage = models.ForeignKey(to=Storage, on_delete=models.CASCADE)
    item = models.CharField(max_length=128)
    amount = models.CharField(max_length=32)
    receive_date = models.DateTimeField(null=True)
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES)
    sended_amount = models.CharField(max_length=255, null=True)
    arrived_amount = models.CharField(max_length=255, null=True)
    comment = models.CharField(max_length=255, null=True)

    objects = managers.ItemDeficitManager()


class ExpenseStatus(models.Model):
    SUCCESS_CHOICES = [
        (False, 'Отказ'),
        (True, 'Принят')
    ]

    expense = models.ForeignKey(to=Expense, on_delete=models.CASCADE)
    success = models.BooleanField(choices=SUCCESS_CHOICES)
    comments = models.JSONField(default=list)

    objects = managers.ExpenseStatusManager()


class ProductRemain(models.Model):
    storage = models.ForeignKey(to=Storage, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    amount = models.IntegerField()

    objects = managers.ProductRemainManager()


class FAQTag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class FAQ(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    tags = models.ManyToManyField(to=FAQTag)

    objects = managers.FAQManager()

app/templates/lk/employees/create.html
{% extends 'base.html' %}

{% block title %}Добавление сотрудника{% endblock %}
{% block page_title %}Добавление сотрудника в базу{% endblock %}

{% block body %}
    <div class="container-xl">
        <div class="card rounded-3">
            <div class="card-body">
                <form action="{% url 'LK:create_employee' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-4">
                        <label for="photo" class="form-label">Фото</label>
                        <input class="form-control" type="file" name="employee_photo" id="employee_photo">
                    </div>
                    <div class="mb-4">
                        <label class="form-label">Фамилия</label>
                        <input class="form-control" name="last-name" placeholder="Введите фамилию" required>
                    </div>
                    <div class="mb-4">
                        <label class="form-label">Имя</label>
                        <input class="form-control" name="first-name" placeholder="Введите имя" required>
                    </div>
                    <div class="mb-4">
                        <label class="form-label">Дата рождения</label>
                        <input class="form-control date-at" name="birth-date" placeholder="Выберите дату рождения"
                               required>
                    </div>
                    <div class="mb-4">
                        <label class="form-label">Адрес проживания</label>
                        <input class="form-control" name="address" placeholder="Введите адрес проживания" required>
                    </div>
                    <div class="mb-4">
                        <label class="form-label">Должность</label>
                        <select class="form-select" name="job-id" placeholder="Выберите должность" required>
                            <option></option>
                            {% for job in jobs %}
                                <option value="{{ job.id }}">{{ job.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="mb-4">
                        <label class="form-label">Заведение</label>
                        <select class="form-select" name="storage-id" placeholder="Выберите заведение" required>
                            <option></option>
                            {% for storage in storages %}
                                <option value="{{ storage.id }}">{{ storage.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="mb-4">
                        <label class="form-label">Номер телефона</label>
                        <div class="input-group mb-2">
                            <span class="input-group-text">+7</span>
                            <input type="tel" inputmode="numeric" name="phone" class="form-control"
                                   data-mask="0000000000" data-mask-visible="true" placeholder="Введите номер телефона"
                                   autocomplete="off" required/>
                        </div>
                    </div>
                    <div class="mb-4">
                        <label class="form-label">Описание сотрудника</label>
                        <input name="description" class="form-control" placeholder="Введите описание"/>
                    </div>
                    <div class="mb-4">
                        <label class="form-label">Статус</label>
                        <select class="form-select" placeholder="Выберите статус" name="status">
                            <option></option>
                            <option value="1">Кандидат</option>
                            <option value="2">Стажер</option>
                            <option value="3">Сотрудник</option>
                            <option value="4">Резерв</option>
                        </select>
                    </div>
                    <div class="mb-1">
                        <button type="submit" class="btn btn-success w-100">Добавить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/lk/employees/edit.html
{% extends 'base.html' %}

{% load names %}

{% block title %}Редактирование сотрудника{% endblock %}
{% block page_title %}Редактирование сотрудника {{ row.fio }}{% endblock %}

{% block body %}
    <div class="container-xl">
        <div class="row">
            <div class="col-6">
                <div class="card rounded-3">
                    <div class="card-body">
                        <form action="{% url 'LK:edit_employee' %}?id={{ row.id }}" method="post"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="mb-4">
                                {% if row.photo.url is not None %}
                                    <div class="mb-4">
                                        <label for="old_employee_photo" class="form-label">Фото сотрудника</label>
                                        <img style="width: 100px; height: 100px;" src="{{ row.photo.url }}"
                                             id="old_employee_photo">
                                    </div>
                                    <label for="employee_photo" class="form-label">Изменить</label>
                                {% else %} <label for="employee_photo" class="form-label">Фото</label> {% endif %}
                                <input class="form-control" type="file" name="employee_photo" id="employee_photo">
                            </div>
                            <div class="mb-4">
                                <label class="form-label">Фамилия</label>
                                <input class="form-control" name="last-name" placeholder="Введите фамилию"
                                       value="{{ row.fio|last_name }}">
                            </div>
                            <div class="mb-4">
                                <label class="form-label">Имя</label>
                                <input class="form-control" name="first-name" placeholder="Введите имя"
                                       value="{{ row.fio|first_name }}">
                            </div>
                            <div class="mb-4">
                                <label class="form-label">Дата рождения</label>
                                <input class="form-control date-at" name="birth_date"
                                       placeholder="Выберите дату рождения" value="{{ row.birth_date|date:'Y-m-d' }}">
                            </div>
                            <div class="mb-4">
                                <label class="form-label">Адрес проживания</label>
                                <input class="form-control" name="address" placeholder="Введите адрес проживания"
                                       value="{{ row.address }}">
                            </div>
                            <div class="mb-4">
                                <label class="form-label">Должность</label>
                                <select class="form-select" name="job_place_id" placeholder="Выберите должность">
                                    <option></option>
                                    {% for job in jobs %}
                                        <option value="{{ job.id }}"
                                                {% if row.job_place.id == job.id %}selected{% endif %}>{{ job.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="mb-4">
                                <label class="form-label">Заведение</label>
                                <select class="form-select" name="storage_id" placeholder="Выберите заведение">
                                    <option></option>
                                    {% for storage in storages %}
                                        <option value="{{ storage.id }}"
                                                {% if storage.id == row.storage.id %}selected{% endif %}>{{ storage.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="mb-4">
                                <label class="form-label">Номер телефона</label>
                                <input type="tel" inputmode="numeric" name="phone" class="form-control"
                                       placeholder="Введите номер телефона" autocomplete="off" value="{{ row.phone }}"/>
                            </div>
                            <div class="mb-4">
                                <label class="form-label">Описание сотрудника</label>
                                <input name="description" class="form-control" placeholder="Введите описание"
                                       value="{% if row.description %}{{ row.description }}{% endif %}"/>
                            </div>
                            <div class="mb-4">
                                <label class="form-label">Статус</label>
                                <select class="form-select mb-1" placeholder="Выберите статус" name="status"
                                        onchange="document.getElementById('status_change_comment').removeAttribute('style')">
                                    <option></option>
                                    <option value="1" {% if row.status == 1 %}selected{% endif %}>Кандидат</option>
                                    <option value="2" {% if row.status == 2 %}selected{% endif %}>Стажер</option>
                                    <option value="3" {% if row.status == 3 %}selected{% endif %}>Сотрудник</option>
                                    <option value="4" {% if row.status == 4 %}selected{% endif %}>Резерв</option>
                                </select>
                                <input class="form-control" id="status_change_comment" name="status_change_comment"
                                       style="display: none;" placeholder="Введите комментарий к смене статуса">
                            </div>
                            <div class="mb-1">
                                <div class="row">
                                    <div class="col-6">
                                        <button type="submit" class="btn btn-success w-100">Сохранить</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card rounded-3">
                    <div class="card-body">
                        <p>Дата последней смены: {{ last_work_day.date_at }}</p>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Дата</th>
                                    <th>Тип</th>
                                    <th>Комментарий</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for log in employee_logs %}
                                    <tr>
                                        <td>{{ log.date_at }}</td>
                                        <td>{{ log.get_type_display }}</td>
                                        <td>{{ log.comment }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Дата</th>
                                <th>Начислено</th>
                                <th>Получено</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for salary in salaries %}
                                <tr>
                                    <td>{{ salary.month }} ({{ salary.year }})</td>
                                    <td>{{ salary.accrued_salary }}</td>
                                    <td>{{ salary.received_salary }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}