app/apps/repairer/urls.py
from django.urls import path

from . import views

app_name = "Repairer"

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('malfunction/complete', views.MalfunctionComplete.as_view(), name="malfunction_complete"),

    path('item_deficit', views.ItemDeficitView.as_view(), name="item_deficit"),
    path('item_deficit/send', views.ItemDeficitSendView.as_view(), name="item_deficit_send")
]

app/config/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('', lambda x: redirect(settings.LOGIN_REDIRECT_URL)),

    path('lk/', include('apps.lk.urls')),
    path('iiko/', include('apps.iiko.urls')),
    path('bar/', include('apps.bar.urls')),
    path('repairer/', include('apps.repairer.urls')),
    path('api/', include('apps.api.urls')),
    path('purchaser/', include('apps.purchaser.urls')),
    path('admin/', include('apps.admin.urls')),
    path('brand_chief/', include('apps.brand_chief.urls')),

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
        re_path(r'^assets/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
    ]

app/apps/repairer/models/managers.py
from django.db import models


class MalfunctionManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().select_related('storage')

app/apps/repairer/models/models.py
from django.db import models

from apps.iiko.models import Storage

from . import managers


class Malfunction(models.Model):
    STATUS_CHOICES = [
        (0, 'Не исправлено'),
        (1, 'Исправлено'),
        (2, 'Одобрено')
    ]

    date_at = models.DateTimeField(auto_now=True)
    storage = models.ForeignKey(Storage, on_delete=models.SET_NULL, null=True)
    photo = models.ImageField(upload_to='malfunction_photos')
    fault_object = models.CharField(max_length=64)
    description = models.TextField()
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES, default=0)
    comment = models.CharField(max_length=128, null=True)

    objects = managers.MalfunctionManager()

app/apps/repairer/views.py
from django.contrib import messages
from django.shortcuts import redirect

from core import exceptions
from core.mixins import BaseLkView
from core.services import item_deficit_service

from apps.lk.models import ItemDeficit

from .models import Malfunction
from .services import RepairerService


class IndexView(BaseLkView):
    template_name = 'repairer/index.html'

    def get_context_data(self, request, **kwargs) -> dict:
        context = super().get_context_data(request, **kwargs)
        context.update({
            "rows": RepairerService().malfunctions_get(storage_id=request.GET.get('storage_id'))
        })

        return context


class MalfunctionComplete(BaseLkView):

    def get(self, request):
        malfunction_id = request.GET.get('id')

        try:
            RepairerService().malfunction_repaired(malfunction_id=malfunction_id)
            messages.success(request, 'Ваш ответ был успешно отправлен.')
        except (exceptions.FieldNotFoundError, exceptions.FieldCannotBeEmptyError, Malfunction.DoesNotExist) as error:
            messages.error(request, error)

        return redirect('/repairer')


class ItemDeficitView(BaseLkView):
    template_name = 'repairer/item_deficit.html'

    def get_context_data(self, request, **kwargs) -> dict:
        context = super().get_context_data(request, **kwargs)
        context.update({
            "rows": item_deficit_service.item_deficit_all()
        })

        return context


class ItemDeficitSendView(BaseLkView):

    def post(self, request):
        context = self.get_context_data(request)

        request_id = request.GET.get('id')

        try:
            receive_status = item_deficit_service.send(request_id=request_id, user=context.get('profile'),
                                                       sended_amount=request.POST.get('sended_amount'),
                                                       comment=request.POST.get('comment'))
            if receive_status:
                messages.success(request, 'Статус успешно обновлен.')
            else:
                messages.error(request, 'Этот запрос уже обработан.')
        except (exceptions.FieldNotFoundError, exceptions.FieldCannotBeEmptyError, ItemDeficit.DoesNotExist) as error:
            messages.error(request, error)

        return redirect('/repairer/item_deficit')

app/templates/repairer/bottom_menu.html
<br> <br><div id="footer-bar" class="footer-bar-5 rounded-3">
    <a href="{% url 'Repairer:index' %}" {% if request.path == '/repairer/' %}class="active-nav"{% endif %}class="active-nav"><i class="fa fa-home"></i><span>Неисправности</span><strong></strong></a>
    <a href="{% url 'Repairer:item_deficit' %}" {% if request.path == '/repairer/item_deficit' %}class="active-nav"{% endif %}class="active-nav"><i class="fa fa-thermometer"></i><span>Нехватка</span><strong></strong></a>
    <a href="{% url 'Repairer:index' %}" {% if request.path == '/repairer/' %}class="active-nav"{% endif %}class="active-nav"><i class="fa fa-list-check"></i><span>Задачи</span><strong></strong></a>
</div>

app/templates/repairer/index.html
{% extends 'repairer/base.html' %}

{% block stylesheets %}
    <link rel="stylesheet" href="/assets/css/magnific-popup.css">
{% endblock %}

{% block body %}
    <div class="container-xl">
        <div class="card rounded-3">
            <div class="card-header card-header-light rounded-top-3">
                Текущие неисправности
            </div>
            <form action="{% url 'Repairer:index' %}" method="post">
                {% csrf_token %}
                <div class="table-responsive">
                    <table class="table card-table table-sm table-bordered table-striped nowrap w-100">
                        <thead>
                        <tr>
                            <th>Фото</th>
                            <th>Дата</th>
                            <th>Заведение</th>
                            <th>Объект</th>
                            <th>Описание</th>
                            <th>Комментарий</th>
                            <th></th>
                        </tr>
                        </thead>
                        {% for row in rows %}
                            {% if row.status != 2 %}
                                <tr class="table-{% if row.status == 0 %}danger{% elif row.status == 1 %}warning{% elif row.status == 2 %}success{% endif %}">
                                    <td><a class="image-popup" title="Фото" href="{{ row.photo.url }}">
                                        <i class="fa fa-camera"></i>
                                    </a></td>
                                    <td>{{ row.date_at|date:'Y-m-d h:i' }}</td>
                                    <td>
                                        <a href="{% url 'Repairer:index' %}?storage_id={{ row.storage.id }}">{{ row.storage.name }}</a>
                                    </td>
                                    <td>{{ row.fault_object }}</td>
                                    <td>{{ row.description }}</td>
                                    <td>{{ row.comment }}</td>
                                    <td>
                                        {% if row.status == 0 %}
                                            <a href="{% url 'Repairer:malfunction_complete' %}?id={{ row.id }}"
                                               class="btn w-100">Завершить</a>
                                        {% elif row.status == 1 %}
                                            <button class="btn w-100" disabled>Отправлено</button>
                                        {% elif row.status == 2 %}
                                            <button
                                                    class="btn w-100" disabled>Завершено
                                            </button>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </table>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="/assets/js/jquery.magnific-popup.min.js"></script>
    <script>
        $('.image-popup').magnificPopup({
            type: 'image'
        });
    </script>
{% endblock %}

app/templates/repairer/item_deficit.html
{% extends 'repairer/base.html' %}

{% block title %}Нехватка{% endblock %}

{% block body %}
    <div class="container-xl">
        {% for row in rows %}
            {% if row.status != 3 %}
                <div class="mb-3">
                    <div class="card rounded-3">
                        <div class="card-body">
                            Дата: {{ row.created_at|date:'Y-m-d H:i' }}<br>
                            Заведение: {{ row.storage.name }}<br>
                            Предмет нехватки: {{ row.item }}<br>
                            Кол-во: {{ row.amount }}<br>
                            {% if row.status == 2 %}Привязано к: {{ row.owner.user.username }}<br>{% endif %}
                            <br>
                            {% if row.status == 1 %}
                                <a data-bs-toggle="modal" data-bs-target="#need-items-send-modal-{{ row.id }}"
                                   class="btn w-100">Отправить</a>
                                <div class="modal modal-blur fade" id="need-items-send-modal-{{ row.id }}"
                                     tabindex="-1" role="dialog" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered" role="document">
                                        <div class="modal-content">
                                            <form action="{% url 'Repairer:item_deficit_send' %}?code={{ code }}&id={{ row.id }}"
                                                  method="post">
                                                {% csrf_token %}
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                        aria-label="Close"></button>
                                                <div class="modal-body text-center py-4">
                                                    <h3>Заполните информацию</h3>
                                                    <div class="text-muted" id="confirm-text">
                                                        <div class="mb-4">
                                                            <input type="tel" inputmode="numeric"
                                                                   class="form-control" name="sended_amount"
                                                                   placeholder="Введите отправленное количество предметов">
                                                        </div>
                                                        <div class="mb-2">
                                                            <input class="form-control" name="comment"
                                                                   placeholder="Введите комментарий (необязательно)">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="modal-footer">
                                                    <div class="w-100">
                                                        <div class="row">
                                                            <div class="col"><a href="#" class="btn w-100"
                                                                                data-bs-dismiss="modal">
                                                                Отмена
                                                            </a></div>
                                                            <div class="col">
                                                                <button id="confirm-delete1"
                                                                        class="btn btn-tabler w-100"
                                                                        data-bs-dismiss="modal">
                                                                    Отправить
                                                                </button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            {% else %}
                                <button class="btn w-100" disabled>Отправлено</button>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}